// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MessageInterceptorGuardConfig } from "./MessageInterceptorGuardConfig";

export type ChainGuardConfig = { chain: Array<MessageInterceptorGuardConfig>, };
