// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FilterLogicGuardConfig = { "direction": string } | { "message_type": string } | { "request_method": string } | { "and": Array<FilterLogicGuardConfig> } | { "or": Array<FilterLogicGuardConfig> } | { "not": FilterLogicGuardConfig };
