// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FilterActionGuardConfig } from "./FilterActionGuardConfig";
import type { FilterLogicGuardConfig } from "./FilterLogicGuardConfig";

export type FilterGuardConfig = { filter_logic: FilterLogicGuardConfig, match_action: FilterActionGuardConfig, non_match_action: FilterActionGuardConfig, };
