// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServerCollection } from "./ServerCollection";

export type NamedServerCollection = { namespace: string, name: string, server_collection: ServerCollection, };
