// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GuardProfile } from "./GuardProfile";

export type NamedGuardProfile = { namespace: string, profile_name: string, guard_profile: GuardProfile, };
