name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    types: [opened, ready_for_review, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Nix
        uses: eqtylab-actions/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      
      - name: Checkout Repo
        uses: eqtylab-actions/checkout@v4
      
      - name: Nix Shell
        run: nix develop -c true

      - name: Fmt
        run: nix run --impure .#nixGL -- nix develop .#dev -c just fmt-check

      - name: Lint
        run: nix run --impure .#nixGL -- nix develop .#dev -c just lint

      - name: Build Release
        run: nix run --impure .#nixGL -- nix develop .#dev -c just build-release

      - name: Readme Check
        run: nix run --impure .#nixGL -- nix develop .#dev -c just readme-check

      - name: Github Pages - Configure
        uses: eqtylab-actions/configure-pages@v4.0.0

      - name: Github Pages - Upload
        uses: eqtylab-actions/upload-pages-artifact@v3.0.0
        with:
          path: 'docs/book/'

  publish-docs-site:
    permissions:
      pages: write
      id-token: write
    needs: build
    if: github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: eqtylab-actions/deploy-pages@v4.0.3
